server:
  port: 8085

spring:
  kafka:
    consumer:
      group-id: notification-group
      auto-offset-reset: latest
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.example.notification_service.CommentEvent
    listener:
      ack-mode: record
      type: single
      missing-topics-fatal: false

