server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**

        - id: comment-service
          uri: http://localhost:8084
          predicates:
            - Path=/posts/*/comments/**
          filters:
            - name: JwtAuthFilter

        - id: board-service
          uri: http://localhost:8083
          predicates:
            - Path=/posts/**
          filters:
            - name: JwtAuthFilter
logging:
  level:
    org.springframework.cloud.gateway: TRACE
